export const ACTIONS = {
  GET_NEXT_LANG: 'SET_NEXT_LANG',
  TOGGLE_FADE: 'TOGGLE_FADE',
  FETCH_ALL_NOTES: 'FETCH_ALL_NOTES',
  UPDATE_NOTE_LIST: 'UPDATE_NOTE_LIST',
  SET_ACTIVE_NOTE_INDEX: 'SET_ACTIVE_NOTE',
  UPDATE_NEW_NOTE_STATE: 'UPDATE_NEW_NOTE_STATE',
  UPDATE_SAVE_NOTE_STATE: 'UPDATE_SAVE_NOTE_STATE',
  ADD_NOTE: 'ADD_NOTE',
  UPDATE_NOTE_TITLE: 'UPDATE_NOTE_TITLE',
  UPDATE_ACTIVE_NOTE_STATE: 'UPDATE_ACTIVE_NOTE_STATE',
  TOGGLE_SAVE_MODAL: 'TOGGLE_SAVE_MODAL',
  SET_NOTE_STATUS: 'SET_NOTE_STATUS',
  UPDATE_NOTE_REV: 'UPDATE_NOTE_REV'
}
