/** Supported ACTIONS. */
export const ACTIONS = {
  GET_NEXT_LANG: 'SET_NEXT_LANG',
  TOGGLE_FADE: 'TOGGLE_FADE',
  UPDATE_NEW_NOTE_STATE: 'UPDATE_NEW_NOTE_STATE',
  UPDATE_SAVE_NOTE_STATE: 'UPDATE_SAVE_NOTE_STATE',
  /** Notes operations */
  NOTES_FETCH_SUCCESS: 'NOTES_FETCH_SUCCESS',
  ADD_NOTE: 'ADD_NOTE',
  SET_SELECTED_NOTE_ID: 'SET_SELECTED_NOTE_ID',
  EDIT_SELECTED_NOTE: 'EDIT_SELECTED_NOTE',
  UPDATE_SELECTED_NOTE_REV: 'UPDATE_SELECTED_NOTE_REV',
  DELETE_SELECTED_NOTE: 'DELETE_SELECTED_NOTE',
  /****/
  TOGGLE_SAVE_MODAL: 'TOGGLE_SAVE_MODAL',
  MODAL_NO_ACTION: 'MODAL_NO_ACTION',
  SET_NOTE_STATUS: 'SET_NOTE_STATUS',
  LOAD_NOTE_CONTENT: 'LOAD_NOTE_CONTENT',
  SAVE_NOTE: 'SAVE_NOTE',
  SAVE_NOTE_FINISHED: 'SAVE_NOTE_FINISHED',
  UPDATE_DELETE_NOTE_STATE: 'UPDATE_DELETE_NOTE_STATE',
  NO_ACTION: 'NO_ACTION',
  NOT_SELECTED_NOTE: '',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  SET_READY_STATUS: 'SET_READY_STATUS'
}
