export const ACTIONS = {
  GET_NEXT_LANG: 'SET_NEXT_LANG',
  TOGGLE_FADE: 'TOGGLE_FADE',
  UPDATE_EDITOR_STATE: 'UPDATE_EDITOR_STATE',
  FETCH_ALL_NOTES: 'FETCH_ALL_NOTES',
  UPDATE_NOTE_LIST: 'UPDATE_NOTE_LIST',
  SET_ACTIVE_NOTE: 'SET_ACTIVE_NOTE',
  UPDATE_NEW_NOTE_STATE: 'UPDATE_NEW_NOTE_STATE',
  UPDATE_SAVE_NOTE_STATE: 'UPDATE_SAVE_NOTE_STATE',
  ADD_NOTE: 'ADD_NOTE'
}
