/** Supported NOTE STATUS. */
export const NOTE_STATUS = {
  NO_OPERATION: 'NO_OPERATION',
  SAVING_NOTE: 'SAVING_NOTE',
  NOTE_SAVE_SUCCESS: 'NOTE_SAVE_SUCCESS',
  NOTE_SAVE_FAIL: 'NOTE_SAVE_FAIL',
  LOADING_NOTE: 'LOADING_NOTE',
  NOTE_LOAD_SUCCESS: 'NOTE_LOAD_SUCCESS',
  NOTE_LOAD_FAIL: 'NOTE_LOAD_FAIL',
  DELETING_NOTE: 'DELETING_NOTE',
  NOTE_DELETE_SUCCESS: 'NOTE_DELETE_SUCCESS',
  NOTE_DELETE_FAIL: 'NOTE_DELETE_FAIL'
}
